info:
  contact: {}
paths:
  /example/hello:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - exmaple
swagger: "2.0"
